export const FailureCode = {
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  REVERSAL_WOULD_MAKE_NEGATIVE: "REVERSAL_WOULD_MAKE_NEGATIVE",
  IDEMPOTENCY_PAYLOAD_CONFLICT: "IDEMPOTENCY_PAYLOAD_CONFLICT",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_CURRENCY_MISMATCH: "WALLET_CURRENCY_MISMATCH",
  DUPLICATE_WALLET: "DUPLICATE_WALLET",
  INVALID_MONEY: "INVALID_MONEY",
  INVALID_KIND: "INVALID_KIND",
  OPENING_NOT_ALLOWED: "OPENING_NOT_ALLOWED",
  REFERENCE_REQUIRED: "REFERENCE_REQUIRED",
  REFERENCE_NOT_FOUND: "REFERENCE_NOT_FOUND",
  REFERENCE_SCOPE_MISMATCH: "REFERENCE_SCOPE_MISMATCH",
  INVALID_REFERENCE_KIND: "INVALID_REFERENCE_KIND",
  ALREADY_REVERSED: "ALREADY_REVERSED",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  PLAYER_WALLET_MISMATCH: "PLAYER_WALLET_MISMATCH",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  TRANSIENT_INFRASTRUCTURE: "TRANSIENT_INFRASTRUCTURE",
} as const;

export type FailureCode = (typeof FailureCode)[keyof typeof FailureCode];
